# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepwater.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deepwater.proto',
  package='deepwater',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x64\x65\x65pwater.proto\x12\tdeepwater\"\x97\x02\n\x03\x43md\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.deepwater.Type\x12\r\n\x05graph\x18\x64 \x01(\t\x12\x13\n\x0binput_shape\x18\x65 \x03(\x05\x12\x13\n\x0bsolver_type\x18\x66 \x01(\t\x12\x15\n\rlearning_rate\x18g \x01(\x02\x12\x10\n\x08momentum\x18h \x01(\x02\x12\x13\n\x0brandom_seed\x18i \x01(\x03\x12\x0f\n\x07use_gpu\x18j \x01(\x08\x12\x12\n\nregression\x18k \x01(\x08\x12\x0e\n\x05sizes\x18\xc9\x01 \x03(\x05\x12\x0e\n\x05types\x18\xca\x01 \x03(\t\x12\x17\n\x0e\x64ropout_ratios\x18\xcb\x01 \x03(\x01\x12\r\n\x04\x64\x61ta\x18\xac\x02 \x03(\x0c\x12\r\n\x04path\x18\x90\x03 \x01(\t*g\n\x04Type\x12\n\n\x06\x43reate\x10\x00\x12\t\n\x05Train\x10\x01\x12\x0b\n\x07Predict\x10\x02\x12\r\n\tSaveGraph\x10\x03\x12\x08\n\x04Save\x10\x04\x12\x08\n\x04Load\x10\x05\x12\x0b\n\x07Success\x10\n\x12\x0b\n\x07\x46\x61ilure\x10\x0b\x42$\n\"hex.genmodel.algos.deepwater.caffeb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='deepwater.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Create', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Train', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Predict', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SaveGraph', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Save', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Load', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Success', index=6, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Failure', index=7, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=312,
  serialized_end=415,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
Create = 0
Train = 1
Predict = 2
SaveGraph = 3
Save = 4
Load = 5
Success = 10
Failure = 11



_CMD = _descriptor.Descriptor(
  name='Cmd',
  full_name='deepwater.Cmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='deepwater.Cmd.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='graph', full_name='deepwater.Cmd.graph', index=1,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_shape', full_name='deepwater.Cmd.input_shape', index=2,
      number=101, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solver_type', full_name='deepwater.Cmd.solver_type', index=3,
      number=102, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='deepwater.Cmd.learning_rate', index=4,
      number=103, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momentum', full_name='deepwater.Cmd.momentum', index=5,
      number=104, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='random_seed', full_name='deepwater.Cmd.random_seed', index=6,
      number=105, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_gpu', full_name='deepwater.Cmd.use_gpu', index=7,
      number=106, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='regression', full_name='deepwater.Cmd.regression', index=8,
      number=107, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sizes', full_name='deepwater.Cmd.sizes', index=9,
      number=201, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='types', full_name='deepwater.Cmd.types', index=10,
      number=202, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout_ratios', full_name='deepwater.Cmd.dropout_ratios', index=11,
      number=203, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='deepwater.Cmd.data', index=12,
      number=300, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='deepwater.Cmd.path', index=13,
      number=400, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=310,
)

_CMD.fields_by_name['type'].enum_type = _TYPE
DESCRIPTOR.message_types_by_name['Cmd'] = _CMD
DESCRIPTOR.enum_types_by_name['Type'] = _TYPE

Cmd = _reflection.GeneratedProtocolMessageType('Cmd', (_message.Message,), dict(
  DESCRIPTOR = _CMD,
  __module__ = 'deepwater_pb2'
  # @@protoc_insertion_point(class_scope:deepwater.Cmd)
  ))
_sym_db.RegisterMessage(Cmd)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"hex.genmodel.algos.deepwater.caffe'))
# @@protoc_insertion_point(module_scope)
